### ISSUE TITLE
No pods

### ISSUE THREAD

**Issue by ghost** [PhilippMatthes/no2#1]
No pods files ;)

**Comment by PhilippMatthes** [comment]
Pod files are now added. Before you use this code, please read the [LICENSE.md](https://github.com/PhilippMatthes/no2/blob/master/LICENSE.md) File.

> Permission is hereby denied, to any person obtaining a copy of this software and associated documentation files (the "Software"), to publish, distribute, sublicense, and/or sell copies of this Software.

Best regards,
Philipp
